name: Build and Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Calculate version
        id: version
        run: |
          BASE_DATE="2025-09-01"
          NOW=$(date -u +"%Y-%m-%d")
          BASE_YEAR=$(date -u -d "$BASE_DATE" +"%Y")
          BASE_MONTH=$(date -u -d "$BASE_DATE" +"%m")
          NOW_YEAR=$(date -u -d "$NOW" +"%Y")
          NOW_MONTH=$(date -u -d "$NOW" +"%m")
          # Remove leading zeros
          BASE_MONTH=$((10#$BASE_MONTH))
          NOW_MONTH=$((10#$NOW_MONTH))
          echo "NOW_MONTH: $NOW_MONTH"
          echo "BASE_MONTH: $BASE_MONTH"
          MAJOR=$((NOW_YEAR - BASE_YEAR))
          MINOR=$(( (NOW_MONTH - BASE_MONTH + 12) % 12 ))
          if [ "$MINOR" -lt 0 ] || [ "$MINOR" -gt 11 ]; then
            MINOR=0
          fi
          PATCH=${{ github.run_number }}
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Calculated version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set npm version
        run: npm version $VERSION --no-git-tag-version

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
